server.port = 8888
spring.application.name = SpringBootAdmin
spring.boot.admin.ui.title = SpringBootAdmin-Server


eureka.instance.preferIpAddress = true
eureka.client.serviceUrl.defaultZone = http://192.168.148.59:1111/eureka/
eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true
